### ISSUE TITLE
Need to add another CT80 class

### ISSUE THREAD

**Issue by DaveOke** [mhrivnak/radiotherm#41]
CT80RevB2v026

**from thermostat.py**
class CT80RevB2v026(CT80RevB):
    MODEL = 'CT80 Rev B V0.26'

**from __init.py__**
from .thermostat import (
    Thermostat,
    CommonThermostat,
    CT30v175,
    CT30v192,
    CT30v194,
    CT30v199,
    CT50v109,
    CT50v188,
    CT50v192,
    CT50v194,
    CT80RevB1v100,
    CT80RevB2v100,
    CT80RevB2v103,
    CT80RevB2v109,
    **CT80RevB2v026,**
)
from . import discover
from . import fields

THERMOSTATS = (
    CT30v175,
    CT30v192,
    CT30v194,
    CT30v199,
    CT50v109,
    CT50v188,
    CT50v192,
    CT50v194,
    CT80RevB1v100,
    CT80RevB2v100,
    CT80RevB2v103,
    CT80RevB2v109,
    **CT80RevB2v026,**
)

**Comment by craftyguy** [comment]
Can you try the master branch here? There was a commit recently to add support for device 'families' (e.g. CT80), so it should no longer be necessary to add every rev/version of a device to have it working in radiotherm.

I've been testing this out on my device, which isn't in the thermostat class, but if I could get a few more people to test it and confirm it works then I will make another release that includes it..

**Comment by dethpickle** [comment]
Hi @craftyguy, I'm looking for something similar - I have firmware v1.04.84 on a CT80 and think that same fix would help me.  It's in the master branch but beyond the latest release (1.4.1).  Any idea when you might bump out a new release?  Since switching to using Hass.io, it's not as easy to include custom or modified libraries from the pypi release.

Thanks for all your work here.

**Comment by craftyguy** [comment]
@dethpickle Yea I may go ahead and make a release. I was hoping at least one other person could confirm it also works for them (it does for my device) before then, but it seems unlikely since the barrier to testing is quite involved (for reasons you point out).

Note that the next release will have a change (2568e1cf747c7acd9e2edcb93ef61c53d0b1d177) which will require changes in Home Assistant's radiotherm wrapper before it can be used. I plan to make that change and submit it to HA, but it'll take some additional time for me to do that.

**Comment by dethpickle** [comment]
Well, breaking changes... :-) no problem for me, as the standard "radiotherm" integration doesn't work at all for me now.  

Regrettably, I've had so little time to play with this since I installed the CT80 over the summer, I've just been RESTing to it directly with NodeRed to take my energy usage out of HA and populate it in the message fields.  But as for actually controlling the thermostat, I haven't had to yet - the perks of living in SoCal.  But, I'm going to need to run the heater one of these days.  That's what I'm preparing for.

I could do the same thing and directly control it, but I'd really rather have the nice built in interface.  Likewise, haven't even gone down the Lovelace hole yet.

**Comment by craftyguy** [comment]
Support for unknown tstats has been merged, and 2.0.0 has been released.

@dethpickle here's the PR to update home-assistant: https://github.com/home-assistant/home-assistant/pull/19107

Hopefully it is merged soon and makes the 0.84 release :)
